version: '3'
services:
  database:
    image: postgres
    container_name: database 
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - morfeus-network

  backend1:
    build:
      context: .
      dockerfile: backend1.dockerfile
    restart: always
    container_name: backend1
    env_file: ".env"
    ports:
      - "3001:3000"
    depends_on:
      - database
    networks:
      - morfeus-network

  backend2:
    build:
      context: .
      dockerfile: backend2.dockerfile
    restart: always
    container_name: backend2
    env_file: ".env"
    ports:
      - "3002:3000"
    depends_on:
      - database
      - backend1
    networks:
      - morfeus-network

  nginx:
    image: nginx:stable-alpine
    restart: always
    container_name: nginx
    ports:
      - 3000:80
    networks:
      - morfeus-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - morfeus-network
    depends_on:
      - nginx

volumes:
  postgres-data:
  redis_data:
    driver: local
networks:
  morfeus-network:
    driver: bridge